name: Deploy to Heroku

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@v2
              with:
                  ref: master

            - name: Push to Heroku
              run: |
                  git fetch origin master --unshallow
                  git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/pagespeed-insights.git master
